spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restocks?serverTimezone=UTC
    username: bogenarc
    password: Tldzmvmfl1!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        #format_sql: true
        use_sql_comments: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
    mode: HTML5
    cache: false
    order: 0
  devtools:
    restart:
      enabled: true
  mvc:
    static-path-pattern: /resources/static/**


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace